name: Auto Release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@master
      - name: Zip Pack
        uses: TheDoctor0/zip-release@main
        with:
          type: "zip"
          filename: "Modernized128x.zip" # default is release.zip
          exclusions: "*.git*"
      - name: Release Pack
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Modernized128x.zip"
          generateReleaseNotes: true
