name: Auto Release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Zip Pack
        uses: TheDoctor0/zip-release@main
        with:
          type: "zip"
          filename: "Modernized128x.zip" # default is release.zip
          exclusions: "*.git*"
      - name: Semantic Version
        id: version
        uses: ncipollo/semantic-version-action@v1.0.1
      - name: Release Pack
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Modernized128x.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: "main"
          tag: ${{ version.outputs.tag }}
          generateReleaseNotes: true
